// Mocks generated by Mockito 5.4.4 from annotations
// in sf_commerce_sdk/test/sf_commerce_sdk_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sf_commerce_sdk/data/cache/cache_memory.dart' as _i3;
import 'package:sf_commerce_sdk/models/responses/category/category.dart'
    as _i10;
import 'package:sf_commerce_sdk/models/responses/product/product.dart' as _i4;
import 'package:sf_commerce_sdk/models/responses/product/product_by_category.dart'
    as _i12;
import 'package:sf_commerce_sdk/models/sf_commerce_config.dart' as _i6;
import 'package:sf_commerce_sdk/repository/auth/auth_repository.dart' as _i5;
import 'package:sf_commerce_sdk/repository/category_repository.dart' as _i9;
import 'package:sf_commerce_sdk/repository/product_repository.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemoryCache_1 extends _i1.SmartFake implements _i3.MemoryCache {
  _FakeMemoryCache_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_2 extends _i1.SmartFake implements _i4.Product {
  _FakeProduct_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i5.AuthRepository {
  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.SfCommerceConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
        returnValueForMissingStub: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
      ) as _i6.SfCommerceConfig);

  @override
  _i8.Future<bool> checkStatus() => (super.noSuchMethod(
        Invocation.method(
          #checkStatus,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
        returnValueForMissingStub: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> anonymousLogin() => (super.noSuchMethod(
        Invocation.method(
          #anonymousLogin,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [CategoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryRepository extends _i1.Mock
    implements _i9.CategoryRepository {
  @override
  _i3.MemoryCache get memoryCache => (super.noSuchMethod(
        Invocation.getter(#memoryCache),
        returnValue: _FakeMemoryCache_1(
          this,
          Invocation.getter(#memoryCache),
        ),
        returnValueForMissingStub: _FakeMemoryCache_1(
          this,
          Invocation.getter(#memoryCache),
        ),
      ) as _i3.MemoryCache);

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.SfCommerceConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
        returnValueForMissingStub: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
      ) as _i6.SfCommerceConfig);

  @override
  _i8.Future<List<_i10.Category>> getRootCategories() => (super.noSuchMethod(
        Invocation.method(
          #getRootCategories,
          [],
        ),
        returnValue: _i8.Future<List<_i10.Category>>.value(<_i10.Category>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i10.Category>>.value(<_i10.Category>[]),
      ) as _i8.Future<List<_i10.Category>>);

  @override
  _i8.Future<List<_i10.Category>> getCategoriesByUrl(String? url) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoriesByUrl,
          [url],
        ),
        returnValue: _i8.Future<List<_i10.Category>>.value(<_i10.Category>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i10.Category>>.value(<_i10.Category>[]),
      ) as _i8.Future<List<_i10.Category>>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i11.ProductRepository {
  @override
  _i3.MemoryCache get memoryCache => (super.noSuchMethod(
        Invocation.getter(#memoryCache),
        returnValue: _FakeMemoryCache_1(
          this,
          Invocation.getter(#memoryCache),
        ),
        returnValueForMissingStub: _FakeMemoryCache_1(
          this,
          Invocation.getter(#memoryCache),
        ),
      ) as _i3.MemoryCache);

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  _i6.SfCommerceConfig get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
        returnValueForMissingStub: _i7.dummyValue<_i6.SfCommerceConfig>(
          this,
          Invocation.getter(#config),
        ),
      ) as _i6.SfCommerceConfig);

  @override
  _i8.Future<List<_i4.Product>> getProducts(List<String>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [ids],
        ),
        returnValue: _i8.Future<List<_i4.Product>>.value(<_i4.Product>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i4.Product>>.value(<_i4.Product>[]),
      ) as _i8.Future<List<_i4.Product>>);

  @override
  _i8.Future<_i4.Product> getProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i8.Future<_i4.Product>.value(_FakeProduct_2(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
        returnValueForMissingStub: _i8.Future<_i4.Product>.value(_FakeProduct_2(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i8.Future<_i4.Product>);

  @override
  _i8.Future<List<_i12.ProductByCategory>> getProductByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductByCategory,
          [category],
        ),
        returnValue: _i8.Future<List<_i12.ProductByCategory>>.value(
            <_i12.ProductByCategory>[]),
        returnValueForMissingStub:
            _i8.Future<List<_i12.ProductByCategory>>.value(
                <_i12.ProductByCategory>[]),
      ) as _i8.Future<List<_i12.ProductByCategory>>);
}
