include: package:very_good_analysis/analysis_options.6.0.0.yaml
 
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
  errors:
    invalid_annotation_target: ignore
    comment_references: ignore