name: sf_commerce_sdk
description: "A new Flutter project."
version: 0.0.1
homepage: https://dcx-coe-exp.pl.s2-eu.capgemini.com/gitlab/mobile/flutter-sfcommercesdk

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.3
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0

